hotfix: Corregir imports de database en RBAC
- permissions.js: Cambiar require('../config/database') -> require('./db')

- roles.routes.js: Cambiar require('../config/database') -> require('../utils/db')

Fix deployment error: Cannot find module '../config/database'

El proyecto usa backend/utils/db.js como modulo de conexion